run:
  deadline: 10m
  skip-dirs:
    - temp
  skip-files:
    - ".*_gen.go$"
  tests: false
  sort-results: true
linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - interfacer
    - golint
    - maligned
    - scopelint
linters-settings:
  cyclop:
    max-complexity: 15