version: "2"
run:
  go: "1.26"
linters:
  default: all
  disable:
    - depguard
    - dupl
    - exhaustruct
    - funlen
    - gochecknoglobals
    - gomodguard
    - ireturn
    - lll
    - mnd
    - tagalign
    - tagliatelle
    - testpackage
    - varnamelen
    - wsl
  settings:
    cyclop:
      max-complexity: 15
    goconst:
      ignore-string-values:
        - 'Host'
    paralleltest:
      ignore-missing: true
  exclusions:
    presets:
      - comments
    rules:
      - path: (.+)_test.go
        linters:
          - canonicalheader
          - containedctx
          - err113
          - errcheck
          - errchkjson
          - forbidigo
          - goconst
          - godot
          - gosec
          - govet
          - maintidx
          - nilnil
          - nlreturn
          - noctx
          - nonamedreturns
          - perfsprint
          - revive
          - staticcheck
          - testifylint
          - wrapcheck
          - wsl_v5
formatters:
  enable:
    - goimports
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
      custom-order: true
  exclusions:
    generated: disable

output:
  sort-order:
    - file
