run:
  go: 1.18
  deadline: 10m
  skip-dirs:
    - temp
  skip-files:
    - ".*_gen.go$"
  tests: false
  sort-results: true
linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - interfacer
    - golint
    - maligned
    - scopelint
linters-settings:
  cyclop:
    max-complexity: 15
  varnamelen:
    max-distance: 10
    ignore-type-assert-ok: true
    ignore-map-index-ok: true
    ignore-decls:
      - ok bool
      - i int
      - e error
      - h http.Handler
      - t time.Time
      - v reflect.Value
      - w io.Writer
      - w http.ResponseWriter
      - rw http.ResponseWriter
      - r *http.Request