version: "2"
run:
  go: "1.23"
  tests: false
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - gochecknoglobals
    - gocognit
    - intrange
    - ireturn
  settings:
    cyclop:
      max-complexity: 18
    varnamelen:
      max-distance: 10
      ignore-type-assert-ok: true
      ignore-map-index-ok: true
      ignore-decls:
        - ok bool
        - i int
        - n int
        - e error
        - h http.Handler
        - t time.Time
        - v reflect.Value
        - w io.Writer
        - w http.ResponseWriter
        - rw http.ResponseWriter
        - r *http.Request
        - wg sync.WaitGroup
        - c chan
        - op string
        - l zerolog.Logger
        - r io.Reader
        - l zerolog.Context
        - s string
        - l string
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - .*_gen.go$
      - temp
formatters:
  enable:
    - goimports
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
      custom-order: true
  exclusions:
    generated: disable
