run:
  go: "1.22"
  tests: false
issues:
  exclude-files:
    - ".*_gen.go$"
  exclude-dirs:
    - temp
linters:
  enable-all: true
  disable:
    - execinquery
    - gochecknoglobals
    - gomnd
    - ireturn
    - exhaustruct
    - gocognit
    - depguard
    - intrange #pending 1.57.3
linters-settings:
  cyclop:
    max-complexity: 18
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/bir/iken)
  varnamelen:
    max-distance: 10
    ignore-type-assert-ok: true
    ignore-map-index-ok: true
    ignore-decls:
      - ok bool
      - i int
      - n int
      - e error
      - h http.Handler
      - t time.Time
      - v reflect.Value
      - w io.Writer
      - w http.ResponseWriter
      - rw http.ResponseWriter
      - r *http.Request
      - wg sync.WaitGroup
      - c chan
      - op string
      - l zerolog.Logger
      - r io.Reader
      - l zerolog.Context
      - s string
      - l string