run:
  go: 1.22
  deadline: 10m
  skip-dirs:
    - temp
  skip-files:
    - ".*_gen.go$"
  tests: false
  sort-results: true
linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - interfacer
    - golint
    - maligned
    - scopelint
    - exhaustivestruct
    - ireturn
    - ifshort
    - deadcode
    - structcheck
    - varcheck
    - nosnakecase
    - exhaustruct
    - gocognit
    - depguard
linters-settings:
  cyclop:
    max-complexity: 18
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/bir/iken)
  varnamelen:
    max-distance: 10
    ignore-type-assert-ok: true
    ignore-map-index-ok: true
    ignore-decls:
      - ok bool
      - i int
      - n int
      - e error
      - h http.Handler
      - t time.Time
      - v reflect.Value
      - w io.Writer
      - w http.ResponseWriter
      - rw http.ResponseWriter
      - r *http.Request
      - wg sync.WaitGroup
      - c chan
      - op string
      - l zerolog.Logger
      - r io.Reader
      - l zerolog.Context
      - s string
      - l string